-- MySQL Script generated by MySQL Workbench
-- Mon Nov 11 23:30:25 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema aCotizar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aCotizar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aCotizar` DEFAULT CHARACTER SET utf8 ;
USE `aCotizar` ;

-- -----------------------------------------------------
-- Table `aCotizar`.`t_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aCotizar`.`t_categoria` (
  `cat_id` INT NOT NULL AUTO_INCREMENT,
  `cat_nom` VARCHAR(45) NULL,
  PRIMARY KEY (`cat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aCotizar`.`t_subcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aCotizar`.`t_subcategoria` (
  `scat_id` INT NOT NULL AUTO_INCREMENT,
  `scat_nom` VARCHAR(45) NULL,
  `cat_id` INT NULL,
  PRIMARY KEY (`scat_id`),
  INDEX `fk_t_subcategoria_t_categoria1_idx` (`cat_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_subcategoria_t_categoria1`
    FOREIGN KEY (`cat_id`)
    REFERENCES `aCotizar`.`t_categoria` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aCotizar`.`t_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aCotizar`.`t_producto` (
  `prod_id` INT NOT NULL AUTO_INCREMENT,
  `prod_nom` TEXT NULL,
  `scat_id` INT NULL,
  PRIMARY KEY (`prod_id`),
  INDEX `fk_t_producto_t_subcategoria1_idx` (`scat_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_producto_t_subcategoria1`
    FOREIGN KEY (`scat_id`)
    REFERENCES `aCotizar`.`t_subcategoria` (`scat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aCotizar`.`t_unidadmedida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aCotizar`.`t_unidadmedida` (
  `um_id` INT NOT NULL AUTO_INCREMENT,
  `um_nom` VARCHAR(45) NULL,
  `um_abr` VARCHAR(45) NULL,
  PRIMARY KEY (`um_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aCotizar`.`t_departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aCotizar`.`t_departamento` (
  `dpto_id` INT NOT NULL AUTO_INCREMENT,
  `dpto_nom` VARCHAR(45) NULL,
  PRIMARY KEY (`dpto_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aCotizar`.`t_provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aCotizar`.`t_provincia` (
  `prov_id` INT NOT NULL AUTO_INCREMENT,
  `prov_nom` VARCHAR(45) NULL,
  `dpto_id` INT NULL,
  PRIMARY KEY (`prov_id`),
  INDEX `fk_t_provincia_t_departamento1_idx` (`dpto_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_provincia_t_departamento1`
    FOREIGN KEY (`dpto_id`)
    REFERENCES `aCotizar`.`t_departamento` (`dpto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aCotizar`.`t_distrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aCotizar`.`t_distrito` (
  `dist_id` INT NOT NULL AUTO_INCREMENT,
  `dist_nom` VARCHAR(45) NULL,
  `prov_id` INT NULL,
  PRIMARY KEY (`dist_id`),
  INDEX `fk_t_distrito_t_provincia1_idx` (`prov_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_distrito_t_provincia1`
    FOREIGN KEY (`prov_id`)
    REFERENCES `aCotizar`.`t_provincia` (`prov_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aCotizar`.`t_persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aCotizar`.`t_persona` (
  `per_id` INT NOT NULL AUTO_INCREMENT,
  `per_ndoc` VARCHAR(11) NULL,
  `per_desc` VARCHAR(25) NULL,
  `per_nom` TEXT NULL,
  `per_ape` TEXT NULL,
  `per_tel` VARCHAR(45) NULL,
  `per_dir` TEXT NULL,
  `dist_id` INT NULL,
  PRIMARY KEY (`per_id`),
  INDEX `fk_t_persona_t_distrito1_idx` (`dist_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_persona_t_distrito1`
    FOREIGN KEY (`dist_id`)
    REFERENCES `aCotizar`.`t_distrito` (`dist_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aCotizar`.`t_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aCotizar`.`t_usuario` (
  `usu_id` INT NOT NULL AUTO_INCREMENT,
  `usu_email` VARCHAR(45) NULL,
  `usu_hash` TEXT NULL,
  `usu_salt` TEXT NULL,
  `usu_est` VARCHAR(45) NULL,
  `usu_tipo` VARCHAR(45) NULL,
  `per_id` INT NULL,
  PRIMARY KEY (`usu_id`),
  INDEX `fk_t_usuario_t_persona1_idx` (`per_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_usuario_t_persona1`
    FOREIGN KEY (`per_id`)
    REFERENCES `aCotizar`.`t_persona` (`per_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aCotizar`.`t_entidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aCotizar`.`t_entidad` (
  `ent_id` INT NOT NULL AUTO_INCREMENT,
  `ent_nom` TEXT NULL,
  `ent_rz` TEXT NULL,
  `ent_ruc` VARCHAR(11) NULL,
  `ent_tipo` VARCHAR(45) NULL,
  `ent_pweb` VARCHAR(45) NULL,
  `ent_dir` VARCHAR(45) NULL,
  `dist_id` INT NULL,
  PRIMARY KEY (`ent_id`),
  INDEX `fk_t_entidad_t_distrito1_idx` (`dist_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_entidad_t_distrito1`
    FOREIGN KEY (`dist_id`)
    REFERENCES `aCotizar`.`t_distrito` (`dist_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aCotizar`.`t_cotizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aCotizar`.`t_cotizacion` (
  `coti_id` INT NOT NULL AUTO_INCREMENT,
  `coti_nro` VARCHAR(45) NULL,
  `coti_fech` DATE NULL,
  `coti_est` VARCHAR(45) NULL,
  `usu_id` INT NULL,
  PRIMARY KEY (`coti_id`),
  INDEX `fk_t_cotizacion_t_usuario1_idx` (`usu_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_cotizacion_t_usuario1`
    FOREIGN KEY (`usu_id`)
    REFERENCES `aCotizar`.`t_usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aCotizar`.`t_cotizaciondetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aCotizar`.`t_cotizaciondetalle` (
  `cdet_id` INT NOT NULL AUTO_INCREMENT,
  `cdet_cant` DECIMAL(10,2) NULL,
  `prod_id` INT NULL,
  `coti_id` INT NULL,
  PRIMARY KEY (`cdet_id`),
  INDEX `fk_t_cotizaciondetalle_t_producto1_idx` (`prod_id` ASC) VISIBLE,
  INDEX `fk_t_cotizaciondetalle_t_cotizacion1_idx` (`coti_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_cotizaciondetalle_t_producto1`
    FOREIGN KEY (`prod_id`)
    REFERENCES `aCotizar`.`t_producto` (`prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_cotizaciondetalle_t_cotizacion1`
    FOREIGN KEY (`coti_id`)
    REFERENCES `aCotizar`.`t_cotizacion` (`coti_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aCotizar`.`t_cotizacionentidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aCotizar`.`t_cotizacionentidad` (
  `cotient_id` INT NOT NULL AUTO_INCREMENT,
  `cotient_fech` DATE NULL,
  `cotient_vali` INT NULL,
  `cotient_est` VARCHAR(45) NULL,
  `coti_id` INT NULL,
  `ent_id` INT NULL,
  PRIMARY KEY (`cotient_id`),
  INDEX `fk_t_cotizacionproveedor_t_cotizacion1_idx` (`coti_id` ASC) VISIBLE,
  INDEX `fk_t_cotizacionproveedor_t_entidad1_idx` (`ent_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_cotizacionproveedor_t_cotizacion1`
    FOREIGN KEY (`coti_id`)
    REFERENCES `aCotizar`.`t_cotizacion` (`coti_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_cotizacionproveedor_t_entidad1`
    FOREIGN KEY (`ent_id`)
    REFERENCES `aCotizar`.`t_entidad` (`ent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aCotizar`.`t_cotizacionentidaddetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aCotizar`.`t_cotizacionentidaddetalle` (
  `cotiedet_id` INT NOT NULL AUTO_INCREMENT,
  `cotient_id` INT NULL,
  `cotiedet_prec` DECIMAL(10,2) NULL,
  `cotie_cant` DECIMAL NULL,
  PRIMARY KEY (`cotiedet_id`),
  INDEX `fk_t_cotizacionproveedordetalle_t_cotizacionproveedor1_idx` (`cotient_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_cotizacionproveedordetalle_t_cotizacionproveedor1`
    FOREIGN KEY (`cotient_id`)
    REFERENCES `aCotizar`.`t_cotizacionentidad` (`cotient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aCotizar`.`t_productosentidadprecio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aCotizar`.`t_productosentidadprecio` (
  `pep_precio` DECIMAL(10,2) NULL,
  `pep_ufda` DATE NULL,
  `prod_id` INT NULL,
  `ent_id` INT NULL,
  `um_id` INT NULL,
  INDEX `fk_t_productosproveedor_t_producto1_idx` (`prod_id` ASC) VISIBLE,
  INDEX `fk_t_productosproveedor_t_entidad1_idx` (`ent_id` ASC) VISIBLE,
  INDEX `fk_t_productosproveedorprecio_t_unidadmedida1_idx` (`um_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_productosproveedor_t_producto1`
    FOREIGN KEY (`prod_id`)
    REFERENCES `aCotizar`.`t_producto` (`prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_productosproveedor_t_entidad1`
    FOREIGN KEY (`ent_id`)
    REFERENCES `aCotizar`.`t_entidad` (`ent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_productosproveedorprecio_t_unidadmedida1`
    FOREIGN KEY (`um_id`)
    REFERENCES `aCotizar`.`t_unidadmedida` (`um_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aCotizar`.`t_personaentidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aCotizar`.`t_personaentidad` (
  `ent_id` INT NULL,
  `per_id` INT NULL,
  INDEX `fk_t_personaentidad_t_entidad1_idx` (`ent_id` ASC) VISIBLE,
  INDEX `fk_t_personaentidad_t_persona1_idx` (`per_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_personaentidad_t_entidad1`
    FOREIGN KEY (`ent_id`)
    REFERENCES `aCotizar`.`t_entidad` (`ent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_personaentidad_t_persona1`
    FOREIGN KEY (`per_id`)
    REFERENCES `aCotizar`.`t_persona` (`per_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
